name: Deploy to InfinityFree
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via FTP
        env:
          FTP_USERNAME: if0_41364183
          FTP_PASSWORD: BBX21eZpmW
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          server-dir: htdocs/
          local-dir: ./
